"""adding columns for measurements

Revision ID: bad2dc957357
Revises: b8b5aaa9f14a
Create Date: 2021-12-19 13:46:21.430941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bad2dc957357'
down_revision = 'b8b5aaa9f14a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('unit', sa.String(length=80), nullable=True))
    op.add_column('measurements', sa.Column('preparation', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurements', 'preparation')
    op.drop_column('measurements', 'unit')
    # ### end Alembic commands ###
