"""column for recipe source

Revision ID: ecf37041cd56
Revises: bad2dc957357
Create Date: 2021-12-24 15:48:31.179227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecf37041cd56'
down_revision = 'bad2dc957357'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('source', sa.String(length=800), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'source')
    # ### end Alembic commands ###
